matrix:
  toolchain: [stable, nightly]
steps:
  build:
    when:
      event: [push, pull_request]
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $toolchain
      - cargo build --release

