matrix:
  RUST_TOOLCHAIN: [stable, beta, nightly]

steps:
  test:
    image: docker.io/rust:bullseye
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST_TOOLCHAIN
      - cargo check -j 4
      - cargo test -j 4
